controller_joint_names: ['', 'Shoulder_Joint1', 'foot_Joint1', 'foot_Joint2', 'Shoulder_Joint2', 'foot_Joint3', 'foot_Joint4', 'Shoulder_Joint3', 'foot_Joint5', 'foot_Joint6', 'Shoulder_Joint4', 'foot_Joint7', 'foot_Joint8', ]
