frames:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 5000  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_1
    pid: {p: 150.0, i: 65.0, d: 0.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_2
    pid: {p: 150.0, i: 65.0, d: 0.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_3
    pid: {p: 150.0, i: 65.0, d: 0.0}
    
