frames:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 5000 
  
  # Position Controllers ---------------------------------------
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: Joint_1
    pid: {p: 150.0, i: 65.0, d: 0.0}
  joint2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: Joint_2
    pid: {p: 150.0, i: 65.0, d: 0.0}
  joint3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: Joint_3
    pid: {p: 150.0, i: 65.0, d: 0.0}
