frames:
  frames_joint_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - Joint_1
      - Joint_2
      - Joint_3


    gains:
      Joint_1:   {p: 5000.0, i: 0.01, d: 100, i_clamp: 0.0}
      Joint_2:   {p: 5000.0, i: 0.01, d: 100, i_clamp: 0.0}
      Joint_3:   {p: 5000.0, i: 0.01, d: 100, i_clamp: 0.0}
      
